---
ignore-from-file: [.gitignore, .yamllintignore]

extends: default

rules:
  document-start: disable
  float-values: enable
  line-length: disable
  octal-values: enable
  truthy:
    check-keys: false
  indentation: disable  # We have a lot of files with weird indentation right now.
