[[PackageOverrides]]
name = "python-apt"
ignore = true
reason = "System package"

[[IgnoredVulns]]
id = "PYSEC-2026-1805"
reason = "Unfixable due to protobuf <6.33 pin for s390x segfault (https://github.com/protocolbuffers/protobuf/issues/24103)"

[[IgnoredVulns]]
id = "GHSA-7gcm-g887-7qv7"
reason = "Unfixable due to protobuf <6.33 pin for s390x segfault (https://github.com/protocolbuffers/protobuf/issues/24103)"
