[project]
name = "charmcraft"
dynamic = ["version"]
description = "The main tool to build, upload, and develop in general the Juju charms."
readme = "README.md"
dependencies = [
    "craft-application~=4.8",
    "craft-cli>=2.15.0",
    "craft-grammar>=2.0.0",
    "craft-parts>=2.2.1",
    "craft-providers>=2.1.0",
    "craft-platforms~=0.5",
    "craft-providers>=2.0.0",
    "craft-store~=3.2",
    "distro>=1.7.0",
    "docker>=7.0.0",
    "humanize>=2.6.0",
    "jsonschema~=4.0",
    "jinja2",
    "pydantic~=2.0",
    "python-dateutil",
    "pyyaml",
    "requests",
    "requests-toolbelt",
    "snap-helpers",
    "tabulate",
    "pip>=24.2",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.12",
]
license = "Apache-2.0"
requires-python = ">=3.10"

[project.scripts]
charmcraft = "charmcraft.application.main:main"

[dependency-groups]
dev = [
    { include-group = "lint" },
    "coverage>=7.6.8",
    "freezegun>=1.5.1",
    "hypothesis>=6.122.1",
    "poetry>=1.8.5",  # Needed for testing the poetry plugin.
    "poetry-plugin-export>=1.8.0",  # Needed for testing the poetry plugin with poetry >= 2.0
    "pyfakefs>=5.7.2",
    "pylint>=3.3.2",
    "pytest>=8.3.4",
    "pytest-check>=2.4.1",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-subprocess>=1.5.2",
    "responses>=0.25.3",
]
docs = [
    "canonical-sphinx[full]~=0.2",
    "pyspelling",
    "autodoc-pydantic~=2.0",
    "sphinx-autobuild~=2024.2",
    "sphinx-pydantic~=0.1",
    "sphinx-toolbox~=3.5",
    "sphinx-lint~=1.0",
    "sphinxcontrib-details-directive",
    "sphinxext-rediraffe==0.2.7",
    "matplotlib",
]
lint = [
    "codespell[toml]",
    { include-group = "types" },
]
types = [
    "mypy[reports]~=1.11",
    "types-python-dateutil",
    "types-PyYAML",
    "types-requests<2.31.0.20240312",  # Frozen until we can get urllib3 v2
    "types-setuptools",
    "types-tabulate",
    "types-urllib3",
]
dev-jammy = [
    # Stay on 2.4 for Jammy
    "python-apt~=2.4.0;sys_platform=='linux'",
]
dev-noble = [
    # 2.7 for Noble
    "python-apt~=2.7.0;sys_platform=='linux'",
]
dev-plucky = [
    # 2.9 for Oracular+
    "python-apt~=2.9.0;sys_platform=='linux'",
]
dev-questing = [
    "python-apt~=3.0.0;sys_platform=='linux'",
]
tics = ["flake8", "pylint"]

[tool.uv]
constraint-dependencies = [
    "tabulate>=0.8.8",
    "matplotlib>=3.7.0",
    "lxml>=5.0.0",
    "numpy>=1.22.0",
    "build>=0.1.0",
    "iniconfig>=1.1.0",
    "lxml>=5.0",
    "pyparsing>=3.0.0",
    "pyproject-hooks>=1.0.0",
    "pyyaml>=5.0",
    "markdown>=3.0",
    "markupsafe>=2.0",
    "regex>=2021.11.10",
    "sphinx-basic-ng>=1.0.0b1",
    "tornado>=4.0",
    "webencodings>=0.4.0",
    "launchpadlib>=1.11",
    "lazr-uri>=1.0.6",
    "libnacl>=2.0",
    "oauthlib>=3.0",
    "setuptools>=65",
    "cffi>=1.15",
    "pynacl>=1.4.0",
    "keyring>=24",
    "jaraco-classes>=3.2",
    "pyxdg>=0.27",
    "pytz>=2020",
    "protobuf>=5.0",
    "overrides>=7.3",
    "requests-unixsocket>=0.3",

    # typing-extensions 4.14.0 interferes with pydantic-core builds
    # https://github.com/python/typing_extensions/issues/615
    "typing-extensions!=4.14.0",
]
conflicts = [
    [
        { group = "dev-jammy" },
        { group = "dev-noble" },
        { group = "dev-plucky" },
        { group = "dev-questing" },
    ]
]

[build-system]
requires = ["setuptools>=69.0", "setuptools_scm[toml]>=7.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
readme = { file = "README.md" }

[tool.setuptools_scm]
write_to = "charmcraft/_version.py"
# the version comes from the latest annotated git tag formatted as 'X.Y.Z'
# version scheme:
#   - X.Y.Z.post<commits since tag>+g<hash>.d<%Y%m%d>
# parts of scheme:
#   - X.Y.Z - most recent git tag
#   - post<commits since tag>+g<hash> - present when current commit is not tagged
#   - .d<%Y%m%d> - present when working dir is dirty
# version scheme when no tags exist:
#   - 0.0.post<total commits>+g<hash>
version_scheme = "post-release"
# deviations from the default 'git describe' command:
# - only match annotated tags
# - only match tags formatted as 'X.Y.Z'
git_describe_command = [
    "git",
    "describe",
    "--dirty",
    "--long",
    "--match",
    "[0-9]*.[0-9]*.[0-9]*",
    "--exclude",
    "*[^0-9.]*",
]

[tool.setuptools.packages.find]
include = ["*craft*"]
namespaces = false

[tool.codespell]
ignore-words-list = "buildd,crate,keyserver,comandos,ro,dedent,dedented,tread,socio-economic"
skip = "requirements*.txt,.tox,.git,build,.*_cache,__pycache__,*.tar,*.snap,*.png,./node_modules,./docs/_build,.direnv,.venv,venv,.vscode,charmcraft.spec"
quiet-level = 3
check-filenames = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = "tests"
xfail_strict = true
addopts = "--ignore=tests/spread"
markers = ["slow: slow tests"]

[tool.coverage.run]
branch = true
omit = ["tests/**"]

[tool.coverage.report]
skip_empty = true
exclude_also = ["if (typing\\.)?TYPE_CHECKING:"]

[tool.pyright]
# strict = ["charmcraft"]
pythonVersion = "3.10"
pythonPlatform = "Linux"
exclude = [
    "**/.*",
    "**/__pycache__",
    # pyright might not like the annotations generated by setuptools_scm
    "**/_version.py",
    "tools/measurements-viewer.py",
]
include = [
    "charmcraft",
    "tests/unit",
    "tests/integration",
]
analyzeUnannotatedFunctions = false
reportIncompatibleVariableOverride = "warning"
reportOptionalMemberAccess = "warning"


[tool.mypy]
python_version = "3.10"
packages = [
    "charmcraft",
    "tests.unit",
    "tests.integration",
]
plugins = ["pydantic.mypy"]
exclude = [
    "build",
    "results",
    "tests",
    "tools",
]
warn_unused_configs = true
warn_redundant_casts = true
strict_equality = true
extra_checks = true
#warn_return_any = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
#disallow_any_generics = true

[[tool.mypy.overrides]]
# Ignore typing errors in most legacy packages until we fix them.
module=[
    "charmcraft.charm_builder",
    "charmcraft.cmdbase",
    "charmcraft.commands.extensions",
    "charmcraft.commands.pack",
    "charmcraft.commands.store",
    "charmcraft.store.registry",
    "charmcraft.store.store",
    "charmcraft.extensions._utils",
    "charmcraft.linters",
    "charmcraft.models.charmcraft",
    "charmcraft.package",
    "charmcraft.providers",
]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["charmcraft"]
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = ["tests.*"]
strict = false

[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = [
    "docs",
    "__pycache__",
    "tools",
    "snap/local",
    "charmcraft/_version.py",  # setuptools_scm generates old-style type annotations.
]

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
# Follow ST063 - Maintaining and updating linting specifications for updating these.
# Handy link: https://docs.astral.sh/ruff/rules/
select = [ # Base linting rule selections.
    # See the internal document for discussion:
    # https://docs.google.com/document/d/1i1n8pDmFmWi4wTDpk-JfnWCVUThPJiggyPi2DYwBBu4/edit
    # All sections here are stable in ruff and shouldn't randomly introduce
    # failures with ruff updates.
    "F",     # The rules built into Flake8
    "E",
    "W",     # pycodestyle errors and warnings
    "I",     # isort checking
    "N",     # PEP8 naming
    "D",     # Implement pydocstyle checking as well.
    "UP",    # Pyupgrade - note that some of are excluded below due to Python versions
    "YTT",   # flake8-2020: Misuse of `sys.version` and `sys.version_info`
    "ANN",   # Type annotations.
    "ASYNC", # Catching blocking calls in async functions
    # flake8-bandit: security testing. https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    # https://bandit.readthedocs.io/en/latest/plugins/index.html#complete-test-plugin-listing
    "S101",
    "S102", # assert or exec
    "S103",
    "S108", # File permissions and tempfiles - use #noqa to silence when appropriate.
    "S104", # Network binds
    "S105",
    "S106",
    "S107", # Hardcoded passwords
    "S110", # try-except-pass (use contextlib.suppress instead)
    "S113", # Requests calls without timeouts
    "S3",   # Serialising, deserialising, hashing, crypto, etc.
    "S5",   # Unsafe cryptography or YAML loading.
    "S602", # Subprocess call with shell=true
    "S701", # jinja2 templates without autoescape
    "BLE",  # Do not catch blind exceptions
    "FBT",  # Disallow boolean positional arguments (make them keyword-only)
    "B0",   # Common mistakes and typos.
    "A",    # Shadowing built-ins.
    "COM",  # Trailing commas
    "C4",   # Encourage comprehensions, which tend to be faster than alternatives.
    "T10",  # Don't call the debugger in production code
    "ISC",  # Implicit string concatenation that can cause subtle issues
    "ICN",  # Only use common conventions for import aliases.
    "INP",  # Implicit namespace packages
    # flake8-pie: miscellaneous linters (enabled individually because they're not really related)
    "PIE790", # Unnecessary pass statement
    "PIE794", # Multiple definitions of class field
    "PIE796", # Duplicate value in an enum (reasonable to noqa for backwards compatibility)
    "PIE804", # Don't use a dict with unnecessary kwargs
    "PIE807", # prefer `list` over `lambda: []`
    # "PIE810", # Use a tuple rather than multiple calls. E.g. `mystr.startswith(("Hi", "Hello"))`
    "PYI",    # Linting for type stubs.
    "PT",     # Pytest
    "Q",      # Consistent quotations
    "RSE",    # Errors on pytest raises.
    "RET",    # Simpler logic after return, raise, continue or break
    # "SLF",    # Prevent accessing private class members.
    "SIM",    # Code simplification
    # "TID",    # Tidy imports
    # The team have chosen to only use type-checking blocks when necessary to prevent circular imports.
    # As such, the only enabled type-checking checks are those that warn of an import that needs to be
    # removed from a type-checking block.
    "TC004",  # Remove imports from type-checking guard blocks if used at runtime
    "TC005",  # Delete empty type-checking blocks
    "ARG",    # Unused arguments
    "PTH",    # Migrate to pathlib
    # "FIX",    # All TODOs, FIXMEs, etc. should be turned into issues instead.
    "ERA",    # Don't check in commented out code
    "PGH",    # Pygrep hooks
    "PL",     # Pylint
    "TRY",    # Cleaner try/except,
    # "FLY",    # Detect things that would be better as f-strings.
    # "PERF",   # Catch things that can slow down the application like unnecessary casts to list.
    "RUF001",
    "RUF002",
    "RUF003", # Ambiguous unicode characters
    "RUF005", # Encourages unpacking rather than concatenation
    "RUF008", # Do not use mutable default values for dataclass attributes
    "B035",   # Don't use static keys in dict comprehensions.
    "RUF013", # Prohibit implicit Optionals (PEP 484)
    "RUF100", # #noqa directive that doesn't flag anything
    "RUF200", # If ruff fails to parse pyproject.toml...
]
ignore = [
    #"E203",  # Whitespace before ":"  -- Commented because ruff doesn't currently check E203
    "E501",   # Line too long (reason: ruff will automatically fix this for us)
    "D105",   # Missing docstring in magic method (reason: magic methods already have definitions)
    "D107",   # Missing docstring in __init__ (reason: documented in class docstring)
    "D203",   # 1 blank line required before class docstring (reason: pep257 default)
    "D213",   # Multi-line docstring summary should start at the second line (reason: pep257 default)
    "D215",   # Section underline is over-indented (reason: pep257 default)
    "A003",   # Class attribute shadowing built-in (reason: Class attributes don't often get bare references)
    "SIM117", # Use a single `with` statement with multiple contexts instead of nested `with` statements
    # (reason: this creates long lines that get wrapped and reduces readability)

    # Ignored due to conflicts with ruff's formatter:
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "COM812", # Missing trailing comma - mostly the same, but marginal differences.
    "ISC001", # Single-line implicit string concatenation.

    # Ignored due to common usage in current code
    "TRY003", # Avoid specifying long messages outside the exception class

    # Charmcraft-specific ignores, to be removed as we modernise the code.
    "ANN0", "ANN2",
    "ARG001", "ARG002", "ARG005",
    "BLE",
    "FBT",
    "N805", "N806",
    "PGH003",
    "PLR0912", "PLR0913", "PLR0915", "PLR1714", "PLR2004", "PLR5501",
    "PLW2901",
    "PT007", "PT011",
    "PTH102", "PTH108", "PTH109", "PTH113", "PTH118", "PTH119", "PTH123",
    "RET505", "RET506", "RET508",
    "S108", "S113", "S324", "S701",
    "SIM102",
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-builtins]
strict-checking = true

[tool.ruff.lint.pydocstyle]
ignore-decorators = [ # Functions with these decorators don't have to have docstrings.
    "typing.overload", # Default configuration
    # The next four are all variations on override, so child classes don't have to repeat parent classes' docstrings.
    "overrides.override",
    "overrides.overrides",
    "typing.override",
    "typing_extensions.override",
]

[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.lint.pep8-naming]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
classmethod-decorators = ["pydantic.validator", "pydantic.root_validator"]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [ # Some things we want for the main project are unnecessary in tests.
    "D",       # Ignore docstring rules in tests
    "ANN",     # Ignore type annotations in tests
    "ARG",     # Allow unused arguments in tests (e.g. for fake functions/methods/classes)
    "INP001",  # Tests don't need to be in packages.
    "S101",    # Allow assertions in tests
    "S103",    # Allow `os.chmod` setting a permissive mask `0o555` on file or directory
    "S108",    # Allow Probable insecure usage of temporary file or directory
    "PLR0913", # Allow many arguments for test functions (useful if we need many fixtures)
    "PLR2004", # Allow magic values in tests
    "SLF",     # Allow accessing private members from tests.
    # Charmcraft-specific ignores, to be removed as we modernise the code.
    "A001", "A002",
    "PT012",
    "S105", "S106",
]
"__init__.py" = [
    "I001", # isort leaves init files alone by default, this makes ruff ignore them too.
    "F401", # Allows unused imports in __init__ files.
]
"charmcraft/utils/platform.py" = [
    "A005", # Allow stdlib shadowing.
]

[[tool.uv.index]]
name = "python-apt-wheels"
url = "https://people.canonical.com/~lengau/python-apt-ubuntu-wheels/"
explicit = true

[tool.uv.sources]
python-apt = { index = "python-apt-wheels" }
