# Copyright 2023-2026 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For further info, check https://github.com/canonical/charmcraft
"""Integration tests for the package service."""

import pathlib
from types import SimpleNamespace

import craft_cli.pytest_plugin
import pytest
import yaml
from craft_application import ServiceFactory

from charmcraft import const


@pytest.fixture
def package_service(service_factory: ServiceFactory):
    return service_factory.get("package")


@pytest.fixture
def fake_lifecycle(tmp_path: pathlib.Path):
    stage_dir = tmp_path / "stage"
    prime_dir = tmp_path / "prime"
    stage_dir.mkdir()
    prime_dir.mkdir()
    return SimpleNamespace(
        prime_dir=prime_dir,
        project_info=SimpleNamespace(
            dirs=SimpleNamespace(stage_dir=stage_dir, prime_dir=prime_dir)
        ),
    )


def test_get_generated_metadata_and_manifest_yaml(
    monkeypatch: pytest.MonkeyPatch,
    package_service,
    service_factory: ServiceFactory,
    fake_lifecycle,
):
    original_get = service_factory.get
    monkeypatch.setattr(
        service_factory,
        "get",
        lambda service_name: fake_lifecycle
        if service_name == "lifecycle"
        else original_get(service_name),
    )

    metadata = yaml.safe_load(package_service.get_metadata_yaml())
    manifest = yaml.safe_load(package_service.get_manifest_yaml())
    project = service_factory.get("project").get().marshal()

    assert metadata["name"] == project["name"]
    assert metadata["summary"] == project["summary"]
    assert metadata["description"] == project["description"]
    assert manifest["charmcraft-started-at"] == "2020-03-14T00:00:00+00:00"
    assert manifest["bases"]


def test_get_metadata_yaml_skips_reactive_generated_metadata(
    emitter: craft_cli.pytest_plugin.RecordingEmitter,
    monkeypatch: pytest.MonkeyPatch,
    package_service,
    service_factory: ServiceFactory,
    fake_lifecycle,
):
    original_get = service_factory.get
    monkeypatch.setattr(
        service_factory,
        "get",
        lambda service_name: fake_lifecycle
        if service_name == "lifecycle"
        else original_get(service_name),
    )

    dirs = fake_lifecycle.project_info.dirs
    dirs.stage_dir.mkdir(exist_ok=True)
    (dirs.stage_dir / const.METADATA_FILENAME).write_text("name: reactive\n")
    service_factory.get("project").get().parts["reactive"] = {"source": "."}

    assert package_service.get_metadata_yaml() is False
    emitter.assert_debug(
        "'metadata.yaml' generated by charm. Not using original project metadata."
    )
