name: Bug report
description: Report a bug
labels: "Bug"
body:
  - type: checkboxes
    id: check-existing-issues
    attributes:
      label: Check existing issues
      options:
        - label: I've verified that this bug isn't described by any existing issues.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      value: >
        <!-- Describe the bug, including any relevant context or screenshots. -->
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      value: >
        <!-- Provide step-by-step instructions to reproduce the bug. -->
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: >
        <!--
          We need to know the context in which Charmcraft failed.
            * Are you running Charmcraft in destructive mode, using LXD or Multipass?
            * What operating system are you running Charmcraft on?
        -->
    validations:
      required: true
  - type: textarea
    id: charmcraft_yaml
    attributes:
      label: charmcraft.yaml
      value: >
        <!-- If the issue is specific to a project, share its `charmcraft.yaml`. This
        field automatically renders as YAML, so you don't need to add special
        formatting. -->
      render: yaml
  - type: textarea
    id: logs
    attributes:
      label: Log output
      value: >
        <!-- Provide any relevant logging. This field automatically renders as
        a log, so you don't need to add special formatting. -->
      render: shell
