# Copyright 2023 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For further info, check https://github.com/canonical/charmcraft

"""Service class for packing."""

from __future__ import annotations

import json
import os
import pathlib
import shutil
from collections.abc import Iterable
from datetime import date, datetime
from typing import TYPE_CHECKING, Literal, cast

import craft_platforms
import yaml
from craft_application import services
from craft_application.services.package import package_file
from craft_cli import emit

import charmcraft
from charmcraft import const, errors, models, utils
from charmcraft.models import lint
from charmcraft.models.manifest import Attribute, Manifest
from charmcraft.models.metadata import CharmMetadata
from charmcraft.models.project import (
    BasesCharm,
    PlatformCharm,
)

if TYPE_CHECKING:
    from charmcraft.services.analysis import AnalysisService


class PackageService(services.PackageService):
    """Business logic for creating packages."""

    def _project_file_path(self, filename: str) -> pathlib.Path:
        """Return the path for a project-local file."""
        return (
            self._services.get("project").resolve_project_file_path().parent / filename
        )

    def _has_reactive_plugin(self) -> bool:
        """Return whether the project uses the reactive plugin."""
        project = cast(
            "BasesCharm | PlatformCharm", self._services.get("project").get()
        )
        plugins = {
            part.get("plugin") or name  # NOTE: Not the same as part.get("plugin", name)
            for name, part in project.parts.items()
        }
        return "reactive" in plugins

    def pack(self, prime_dir: pathlib.Path, dest: pathlib.Path) -> list[pathlib.Path]:
        """Create one or more packages as appropriate.

        :param prime_dir: Directory path to the prime directory.
        :param dest: Directory into which to write the package(s).
        :returns: A list of paths to created packages.
        """
        return [self.pack_charm(prime_dir, dest)]

    def pack_charm(
        self, prime_dir: pathlib.Path, dest_dir: pathlib.Path
    ) -> pathlib.Path:
        """Pack a prime directory as a charm for a given set of bases."""
        charm_name = self.get_charm_name()
        charm_path = dest_dir / charm_name
        emit.progress(f"Packing charm {charm_name}")
        utils.build_zip(charm_path, prime_dir)

        return charm_path

    def get_charm_name(self) -> str:
        """Get a charm file name for the appropriate set of run-on bases."""
        name = self._services.get("project").get().name
        platform = self._services.get("build_plan").plan()[0].platform
        platform = platform.replace(":", "-")
        return f"{name}_{platform}.charm"

    @property
    def metadata(self) -> CharmMetadata:
        """Metadata model for this project."""
        return CharmMetadata.from_charm(
            cast("BasesCharm | PlatformCharm", self._services.get("project").get())
        )

    @package_file(const.METADATA_FILENAME)
    def get_metadata_yaml(self, partition: str | None = None) -> str | Literal[False]:
        """Get the mediated metadata.yaml contents."""
        metadata_path = self._project_file_path(const.METADATA_FILENAME)

        if self._has_reactive_plugin():
            stage_dir = self._services.get("lifecycle").project_info.dirs.stage_dir
            if (stage_dir / const.METADATA_FILENAME).exists():
                emit.debug(
                    f"{const.METADATA_FILENAME!r} generated by charm. Not using original project metadata."
                )
                return False
            if metadata_path.is_file():
                return metadata_path.read_text()
            return yaml.safe_dump(self.metadata.marshal(), sort_keys=True)

        if metadata_path.is_file():
            return metadata_path.read_text()

        return yaml.safe_dump(self.metadata.marshal(), sort_keys=True)

    def _get_existing_manifest_timestamp(self) -> str | None:
        """Get the charmcraft_started_at timestamp from an existing manifest.

        Returns the timestamp if a manifest.yaml exists in the prime directory,
        or None if no manifest exists. This enables stable timestamps across
        repeated pack runs when the lifecycle is skipped.
        """
        prime_dir = self._services.get("lifecycle").prime_dir
        manifest_path = prime_dir / const.MANIFEST_FILENAME
        if manifest_path.is_file():
            try:
                existing = yaml.safe_load(manifest_path.read_text())
                if isinstance(existing, dict):
                    started_at = existing.get("charmcraft-started-at")
                    if started_at is not None:
                        if isinstance(started_at, datetime | date):
                            return started_at.isoformat()
                        return str(started_at)
            except yaml.YAMLError:
                pass
        return None

    def _get_ignored_manifest_checks(
        self, project: BasesCharm | PlatformCharm
    ) -> set[str]:
        """Get ignored lint and attribute checks for manifest generation."""
        if not project.analysis:
            return set()

        return {
            *project.analysis.ignore.linters,
            *project.analysis.ignore.attributes,
        }

    def _render_manifest_yaml(self, manifest: Manifest) -> str:
        """Render manifest.yaml contents.

        We need to include unset/default values in order to ensure that the
        architecture is included on each base in the manifest, even when the
        architectures are inferred. However, we also need to exclude Nones so that
        image-info isn't included in manifest.yaml if it doesn't exist.
        """
        return utils.dump_yaml(
            manifest.model_dump(
                mode="json",
                by_alias=True,
                exclude_unset=False,
                exclude_none=True,
            )
        )

    @package_file(const.MANIFEST_FILENAME)
    def get_manifest_yaml(self, partition: str | None = None) -> str:
        """Get the mediated manifest.yaml contents.

        This method is decorated with @package_file to participate in ST160's
        conditional repack logic. For timestamp stability, the charmcraft_started_at
        value is reused from the existing manifest when available, preventing
        unnecessary repacks on repeated pack runs.
        """
        project = cast(
            "BasesCharm | PlatformCharm", self._services.get("project").get()
        )
        analysis_svc = cast("AnalysisService", self._services.get("analysis"))
        lint_results = list(
            analysis_svc.lint_directory(
                self._services.get("lifecycle").prime_dir,
                ignore=self._get_ignored_manifest_checks(project),
            )
        )

        started_at = self._get_existing_manifest_timestamp()
        if started_at is None:
            started_at = str(
                self._services.get("state").get("charmcraft", "started_at")
            )

        return self._render_manifest_yaml(
            self.get_manifest(lint_results, started_at=started_at)
        )

    def _write_file_or_object(
        self, model: dict | None, filename: str, dest_dir: pathlib.Path
    ) -> None:
        """Write a yaml file to the destination directory if the given object is not None.

        This function prefers copying the file over, but will generate YAML from the given
        model otherwise.

        :param model: The dictionary to write (or None)
        :param filename: The name of the file to copy or write.
        :param dest_dir: The path of the destination directory.
        """
        if not model:
            return
        dest_dir.mkdir(parents=True, exist_ok=True)
        source_path = self._project_file_path(filename)
        dest_path = dest_dir / filename
        if source_path.is_file():
            shutil.copyfile(source_path, dest_path)
            return
        with dest_path.open("wt+") as dest_file:
            yaml.safe_dump(model, dest_file)

    def get_manifest(
        self,
        lint_results: Iterable[lint.CheckResult],
        *,
        started_at: str | None = None,
    ) -> Manifest:
        """Get the manifest for this charm."""
        attributes = [
            Attribute(name=result.name, result=result.result)
            for result in lint_results
            if result.check_type == lint.CheckType.ATTRIBUTE
        ]

        if image_info := os.getenv(const.IMAGE_INFO_ENV_VAR):
            try:
                image_info = json.loads(image_info)
            except json.decoder.JSONDecodeError as exc:
                msg = f"Failed to parse the content of {const.IMAGE_INFO_ENV_VAR} environment variable"
                raise errors.CraftError(msg) from exc

        bases = self.get_manifest_bases()

        if started_at is None:
            started_at = str(self._services.get("state").get("charmcraft", "started_at"))

        return Manifest(
            charmcraft_version=charmcraft.__version__,
            charmcraft_started_at=started_at,
            analysis={"attributes": attributes},
            image_info=image_info,
            bases=bases,
        )

    def get_manifest_bases(self) -> list[models.Base]:
        """Get the bases used for a charm manifest from the project."""
        project = cast(
            "BasesCharm | PlatformCharm", self._services.get("project").get()
        )
        build_item = self._services.get("build_plan").plan()[0]
        if isinstance(project, BasesCharm):
            run_on_bases = []
            for project_base in project.bases:
                for build_base in project_base.build_on:
                    if build_base.name != build_item.build_base.distribution:
                        continue
                    if build_base.channel != build_item.build_base.series:
                        continue
                    if build_item.build_on not in build_base.architectures:
                        continue
                    run_on_bases.extend(project_base.run_on)
            if not run_on_bases:
                raise RuntimeError("Could not determine run-on bases.")
            return run_on_bases
        if isinstance(project, PlatformCharm):
            archs = [str(build_item.build_for)]

            # single base recipes will have a base
            if project.base:
                return [models.Base.from_str_and_arch(project.base, archs)]

            # multi-base recipes may have the base in the platform name
            platform_label = build_item.platform
            if base := craft_platforms.parse_base_and_name(platform_label)[0]:
                return [
                    models.Base(
                        name=base.distribution,
                        channel=base.series,
                        architectures=archs,
                    )
                ]

            # Otherwise, retrieve the build-for base from the platform in the project.
            # This complexity arises from building on devel bases - the BuildInfo
            # contains the devel base and not the compatibility base.
            platform = project.platforms.get(platform_label)
            if platform and platform.build_for:
                if base := craft_platforms.parse_base_and_architecture(
                    platform.build_for[0]
                )[0]:
                    return [
                        models.Base(
                            name=base.distribution,
                            channel=base.series,
                            architectures=archs,
                        )
                    ]

        raise TypeError(f"Unknown charm type {project.__class__}, cannot get bases.")

    def write_metadata(self, path: pathlib.Path) -> None:
        """Write additional charm metadata.

        Note: manifest.yaml is now generated via the @package_file-decorated
        get_manifest_yaml() method as part of ST160's mediated packaging flow.
        This method handles metadata.yaml, actions.yaml, and config.yaml.

        :param path: The path to the prime directory.
        """
        project = cast(
            "BasesCharm | PlatformCharm", self._services.get("project").get()
        )
        path.mkdir(parents=True, exist_ok=True)
        svc = cast("AnalysisService", self._services.get("analysis"))
        lint_results = svc.lint_directory(
            self._services.get("lifecycle").prime_dir,
            ignore=self._get_ignored_manifest_checks(project),
        )
        manifest = self.get_manifest(lint_results)
        self._write_asset(
            self._render_manifest_yaml(manifest),
            path / const.MANIFEST_FILENAME,
        )

        project_dict = project.marshal()
        is_reactive = self._has_reactive_plugin()
        stage_dir = self._services.get("lifecycle").project_info.dirs.stage_dir

        metadata = self.get_metadata_yaml()
        if metadata is not False:
            self._write_asset(metadata, path / const.METADATA_FILENAME)

        if is_reactive and (stage_dir / const.JUJU_ACTIONS_FILENAME).exists():
            emit.debug(
                f"{const.JUJU_ACTIONS_FILENAME!r} generated by charm. Skipping generation."
            )
        elif actions := cast(dict | None, project_dict.get("actions")):
            self._write_file_or_object(actions, "actions.yaml", path)
        if is_reactive and (stage_dir / const.JUJU_CONFIG_FILENAME).exists():
            emit.debug(
                f"{const.JUJU_CONFIG_FILENAME!r} generated by charm. Skipping generation."
            )
        elif config := cast(dict | None, project_dict.get("config")):
            self._write_file_or_object(config, "config.yaml", path)
