StylesPath = styles
MinAlertLevel = suggestion
Vocab = Canonical
IgnoredClasses = woke-ignore, vale-ignore

[*.{md,txt,rst,html}]
BasedOnStyles = Canonical

# this enumerates all of the current rules with their suggested
# severity level. This makes it easier to edit for specific use cases

Canonical.000-US-spellcheck = error
Canonical.003-Ubuntu-names-versions = error              
Canonical.005-Industry-product-names = warning            
Canonical.006-Contractions-forbidden = warning             
Canonical.007-Headings-sentence-case = warning           
Canonical.008-Headings-no-period = suggestion               
Canonical.009-Headings-no-links = warning                
Canonical.010-Punctuation-double-spaces = warning         
Canonical.012-Date-format = warning
Canonical.013-Spell-out-numbers-below-10 = suggestion
Canonical.014a-Numbers-greater-than-nine-should-be-in-numeric-form = suggestion
Canonical.014b-Numbers-with-five-or-more-digits-must-have-comma-separators  = suggestion
Canonical.015-No-prompts-in-comments = warning
Canonical.016-No-inline-comments = suggestion
Canonical.017a-Suggest-code-over-25-lines = suggestion
Canonical.017b-Warn-code-over-35-lines = warning
Canonical.019-no-google-drive-images = error
Canonical.025a-latinisms-with-english-equivalents = suggestion
Canonical.025b-latinisms-to-reconsider = suggestion
Canonical.025c-latinisms-to-avoid = suggestion
Canonical.026-hints-tips = suggestion
Canonical.400-Enforce-inclusive-terms = error
Canonical.500-Repeated-words = warning


[*.md]
BasedOnStyles = Canonical

# Ignore custom spelling role
TokenIgnores = ({(vale-ignore|woke-ignore)}`.+?`)

# Ignore opening colon-fenced (:::) lines and colon-fenced literal directives
# The listed directives must be in sync with the [*.rst] `BlockIgnores`
BlockIgnores = (::::*[^\n]*), \
(?s)(::::*) *{(?:code-block|code|prompt|sourcecode|terminal|toctree)}[^\n]*\n(?:(?!\1$)[^\n]*\n)*\1 *


[*.rst]
BasedOnStyles = Canonical

# Ignore custom spelling role
TokenIgnores = (:(vale-ignore|woke-ignore):`.+?`)
# Ignore technical roles
TokenIgnores = (:relatedlinks:)
TokenIgnores = (:(command|envvar|file|kbd|literal|literalref|math|option|program|regexp|samp|token)?:`.+?`)
# Ignore directives
TokenIgnores = (.. \w+::)
# Ignore options
TokenIgnores = (:\w+: \w+), (:\w+:)
# Ignore external links
TokenIgnores = (\`\w+\`_)

# Spelling not respecting code blocks
# The listed directives must be in sync with the [*.md] `BlockIgnores`
BlockIgnores = (?s)\.\. (code-block|code|prompt|sourcecode|terminal|toctree):: ?[^\n]*\n( *:[\w-]+: *[^\n]+\n)*\n( +[^\n]+\n|\n)*
