# Copyright 2020 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For further info, check https://github.com/canonical/charmcraft
name: charmcraft
base: core20
summary: Charmcraft supports Kubernetes operator development and collaboration
license: Apache-2.0
description: |
  Charmcraft enables collaboration between operator developers, and
  publication on Charmhub.io, home of the Open Operator Collection.

  Use `charmcraft` to:

   * Init a new charm file structure
   * Build your Kubernetes operator charm package
   * Register your charm name on Charmhub
   * Upload your charm to Charmhub
   * Release your charm into channels

  You can use charmcraft with operators written in any language but we
  recommend the Python Operator Framework from https://pypi.org/project/ops/
  developed at https://github.com/canonical/operator for ease of development
  and collaboration.

  Charmcraft and the Python Operator Framework extend the operator pattern
  beyond Kubernetes with universal operators that drive Linux and
  Windows apps. The universal operator pattern is very exciting for
  multi-cloud application management.

adopt-info: charmcraft  # look for 'snapcraftctl set-*' in the charmcraft part
architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
  # - build-on: i386  # there is no i386 core20

apps:
  charmcraft:
    command: bin/python3 $SNAP/bin/charmcraft
    completer: completion.bash
    environment:
      # have the cache outside of the version dirs (avoids keeping N copies)
      XDG_CACHE_HOME: $SNAP_USER_COMMON/cache
      # same for config
      XDG_CONFIG_HOME: $SNAP_USER_COMMON/config
      # just drop the logs here for now (this will change; see #53)
      TMPDIR: $SNAP_USER_COMMON
      # help git find its stuff
      GIT_TEMPLATE_DIR: $SNAP/git/templates
      GIT_EXEC_PATH: $SNAP/git/git-core

grade: stable
confinement: classic

parts:
  # Classic core20 snaps require staged python.
  python3:
    plugin: nil
    build-packages:
      - python3-dev
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-minimal
      - libpython3.8-stdlib
      - python3.8-minimal
      - python3-distutils
      - python3-minimal
      - python3-pkg-resources
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
    override-build: |
      snapcraftctl build
      install -D -m 0755 $SNAPCRAFT_PROJECT_DIR/snap/local/sitecustomize.py $SNAPCRAFT_PART_INSTALL/usr/lib/python3.8/sitecustomize.py

  charmcraft:
    after: [python3]
    source: .
    plugin: python
    requirements:
      - requirements-focal.txt
      - requirements.txt
    build-packages:
      - libffi-dev
      - libapt-pkg-dev
    stage-packages:
      - git
      - apt
      - apt-transport-https
      - apt-utils
    # snapcraft uses venv, which doesn't pull in wheel (as opposed to virtualenv)
    # so then 'pip install PyYAML' gets cross.
    python-packages: [wheel]
    build-environment:
      - LDFLAGS: -L/usr/lib/python3.8
      - CPPFLAGS: -I/usr/include/python3.8
    override-pull: |
      # do the usual pull stuff
      snapcraftctl pull
      # set the version
      snapcraftctl set-version "$( python3 -c 'import charmcraft; print(charmcraft.__version__)' )"
    override-build: |
      snapcraftctl build
      # why is this needed?
      cp -v completion.bash ../install
      # python3 fixup symlink (snapcraft bug)
      ln -sf ../usr/bin/python3.8 $SNAPCRAFT_PART_INSTALL/bin/python3
    organize:
      # move things around so they're tidier
      usr/lib/git-core: git/git-core
      usr/share/git-core/templates: git/templates
      usr/bin/git: bin/git
      lib/python3.8/site-packages: lib/
