name: Check policy
on:
  pull_request:
  push:
    branches:
      - main
      - hotfix/*
      - work/check-policy # For development

jobs:
  filter:
    runs-on: ubuntu-slim
    outputs:
      source-files: ${{ steps.filter.outputs.source-files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          # Combine multiple negation checks into a union (¬A ∧ ¬B ∧ ¬C), because individual entries are checked independently (A ∨ B ∨ C).
          # If we ever need to filter only for docs, glob 'docs/**/*' and '**/*.md'
          filters: |
            source-files:
              - '!({docs/**,*.md,**/*.md,.readthedocs.yaml})'
  policy:
    uses: canonical/starflow/.github/workflows/policy.yaml@main
    needs: filter
    if: ${{ needs.filter.outputs.source-files }}
  python-scans:
    name: Security scan
    uses: canonical/starflow/.github/workflows/scan-python.yaml@main
    needs: filter
    if: ${{ needs.filter.outputs.source-files }}
    with:
      packages: python-apt-dev
      # 1. Ignore requirements files in spread tests, as some of these intentionally
      #    contain vulnerable versions.
      # 2. Docs contain requirements.txt files that don't specify versions.
      osv-extra-args: "--config=osv-scanner.toml"
      osv-exclude-paths: |
        docs
        tests/spread
      uv-export-no-groups: |
        docs
        docs-starter-pack
