# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
  workflow_call:
  # TODO: Remove this once we're correctly configured.
  push:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.50.1
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
