name: Schema
on: [pull_request]

env:
  CHARMCRAFT_JSON: schema/charmcraft.json

jobs:
  diff-schema:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout rockcraft
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ${{ steps.runner-info.outputs.cache-hash }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run generator script
        run: |
          uv run --frozen --no-dev --extra apt-jammy \
            python tools/schema.py > generated_schema.json

      - name: Check with stored schema
        run: |
          test -f $CHARMCRAFT_JSON &&
          diff generated_schema.json $CHARMCRAFT_JSON

  validate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Charmcraft
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install ajv cli
        run: npm install -g ajv-cli

      - name: Run ajv
        run: |
          # Don't fail immediately if one validation fails
          EXIT_CODE=0
          for proj_file in tests/spread/smoketests/basic/charmcraft*; do
            if ! ajv validate -s $CHARMCRAFT_JSON \
              -d $proj_file \
              --strict=false --spec=draft2020; then
              EXIT_CODE=1
            fi
          done
          exit $EXIT_CODE
