name: TICS
on:
  push:
    branches:
      - "main"
      # For troubleshooting
      - "work/tiobe**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    permissions:
      contents: read
    uses: canonical/starflow/.github/workflows/tics.yaml@main
    with:
      project: "charmcraft"
    secrets:
      TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}
