name: TIOBE TiCS

on:
  push:
    branches:
      - "work/tics"
  pull_request:
    paths:
      - .github/workflows/tics.yaml
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

env:
  PYTEST_ADDOPTS: -m 'not slow'

jobs:
  tics:
    uses: lengau/starflow/.github/workflows/tics.yaml@work/tics
    with:
      project: charmcraft
      platform-tags: '"ubuntu-24.04"'
